### ISSUE TITLE
Enhancement Request: Allow overrides from input msg

### ISSUE THREAD

**Issue by TotallyInformation** [bladerunner2020/node-red-contrib-isonline#1]
Hi Alex, again many thanks for your node, I'm already finding it very useful.

I do have a couple of requests though if you have time at some point.
- Accept msg.url on the inbound msg, use this if the url in the node is blank
- Accept msg.topic on the inbound msg and pass through to output msg. (Actually, I'm not sure whether it already does this. Sorry I should have checked first).

These would add some great flexibility to the node and allow an upstream function node for example to read any number of URL's from a list, fire a check to each one with a suitable topic so that a single Is Online followed by a single MQTT node would be all that is required to gather on/off-line information for a load of services.

I've already got a flow containing 5 is online nodes each with a change node after it setting the topic and trying (see my other email reply to Dave) to change the boolean to "Online" and "Offline" which I use in my MQTT setup. I've a load of other services I want to check already but it is going to get out of hand. That will grow even further soon as I've ordered some ESP WiFi devices.

If you really have time on your hands ;-) An extra enhancement would be to provide 2 inputs in the node that can output any of the standard output types (see the inject node for example) - string, boolean, number, JSON, msg., flow., global.  Then people could output whatever they wanted for the true and false returns.

Cheers, Julian.

**Comment by bladerunner2020** [comment]
Thanks for positive comments!
Let me clarify your feature requests.
1. Accept msg.url: I see two options here - ether to use msg.url or to have a checkbox in node configuration "Use URL from msg.payload". In the second option you just can put URL in the message payload. Which is more preferable option in your opinion?
2. Msg.topic should not be changed.
3. msg.payload is not changed if you select 2nd or 3rd action option. Actually I use this feature when for example I want to send an email alert and want to be sure that the Internet is up - just use **is online** node before **email** node with action option pass through if online. 
4. There is msg.online property that is always set. I could add always pass through option to node config. So msg.payload is unchanged and you can check status using msg.online property. What do you think, would it work for you?

**Comment by TotallyInformation** [comment]
Hi Alex,
1. I wouldn't bother with a checkbox. Just allow the override if the nodes url field is left blank and add that as an explanation in the help text. This is a common pattern in Node-Red.
2. I will test, thanks for the clarification.
3. I get that, in the cases I'm thinking of, I _want _ to change the payload because the default payload is not the payload I need to pass directly to the downstream MQTT node. The ability to be more flexible with the output saves having to put an additional downstream change node in the flow. As your flows get more complex, saving a step can be really helpful in keeping things comprehensible.
4. Actually, it would be better to leave the msg.online unchanged and allow override of the payload. This is because it is the payload that is used by most nodes so if I need to send something specific (e.g. not true/false) to the next node in the flow, currently I have to add an additional change, switch node or function node.

Thanks for considering this.

**Comment by bladerunner2020** [comment]
@TotallyInformation,
1 - ok. added as feature request.
3 - am i right that you would like to be able to have in the node configuration 2 additional fields: 
       change msg.payload if online to: .....
       change msg.payload if offline to: ....
Something like node change?
4. Unless you use option True or False, msg is not changed and msg.online has true or false status. As far as I understand you 3 and 4 is the same.

I am planning to add option "Always pass through" right now. Adding node Change features requires more work so I am planning to do it in the later versions.

**Comment by TotallyInformation** [comment]
Yup 3/4 are really the same.
3. Yes, correct.

Thanks for listening. It's a great addition to the family of nodes and has a central role in my home hub now.
